user:
  name: 梦洁

spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 1000
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
  zipkin:
    base-url: http://localhost:9412
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1      
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
feign:
  hystrix:
    enabled: true
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8861/eureka